### ISSUE TITLE
代码clone到本地之后提示Cannot resolve symbol 'String'

### ISSUE THREAD

**Issue by liudaolunboluo** [ykdsg/GenerateO2O-2021#1]
本地选择了Idea了sdk，然后GenerateAction类里有关jdk的类比如String或者StringBuilder全部报错Cannot resolve symbol ，但是似乎不影响运行和编译。idea版本2021.2.1

**Comment by ykdsg** [comment]
我本地没有出现，build.gradle 里面配置了，应该是支持，重新加载下试试。
