### ISSUE TITLE
能否支持这种写法呢？

### ISSUE THREAD

**Issue by meidea** [ykdsg/GenerateO2O-2021#3]
```java
@NotNull
public TestModel create(@NotNull TestDTO dto) {

}
```

1. 方法不是static
2. 参数前可能有注解

**Comment by ykdsg** [comment]
测试了一下，这个目前还不支持，主要是不支持注解，因为实现原理是重写了这个方法，当初设计的时候没有考虑注解的情况。可以给点时间研究下。

**Comment by ykdsg** [comment]
重新改造了一下，可以试一下最新的版本，插件中心还没上传，可以试一下本地安装。
https://github.com/ykdsg/GenerateO2O-2021/releases/tag/v2.2

**Comment by meidea** [comment]
试了下，可以了，非常感谢！
